### ISSUE TITLE
Cypress Setup

### ISSUE THREAD

**Issue by natterstefan** [natterstefan/nextjs-template#4]
# TASK

## Tasks

- [x] TS: make sure `expect` is derived from `jest`'s types in `src/**/__tests__/*` => resolved with https://github.com/natterstefan/nextjs-template/commit/8d7488c057d0a1f3949d05a6aff8f0e3fd2f3219
  - https://github.com/cypress-io/cypress-and-jest-typescript-example (via https://github.com/nrwl/nx/issues/892#issuecomment-604150134)
  - https://github.com/cypress-io/cypress-and-jest-typescript-example/issues/25#issuecomment-550287522
  - https://stackoverflow.com/questions/58999086/cypress-causing-type-errors-in-jest-assertions
  - https://www.typescriptlang.org/tsconfig#types: "When you have this option set, by not including a module in the types array it: Will not add globals to your project (e.g process in node, or expect in Jest)"
- [x] TS: Fix `cypress/integration/api/probe-status.spec.ts(8,1): error TS1208: 'probe-status.spec.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.` ==> resolved https://github.com/natterstefan/nextjs-template/commit/8d7488c057d0a1f3949d05a6aff8f0e3fd2f3219#diff-7c73a5b98f30e40574b7149a83a19e335c5ee48b8c9c58e4e6cbfe6a07777037R13
- [ ] Add component Unit-Test example
  - https://www.npmjs.com/package/@cypress/react
  - https://docs.cypress.io/examples/examples/recipes#Unit-Testing
  - https://docs.cypress.io/guides/component-testing/introduction#What-is-Component-Testing
  - Example: https://github.com/cypress-io/cypress/blob/254eb47d91c75a9f56162e7493ab83e5be169935/npm/react/examples/nextjs/cypress/components/Router.spec.jsx
- [ ] add testing-library
  - [ ] add cypress-testing-library https://testing-library.com/docs/cypress-testing-library/intro/
- [ ] add more plugins/settings
  - https://github.com/cypress-io/cypress/issues/2024#issuecomment-754571301
- [ ] support `__cypress__` in `src/*`?
  - https://github.com/cypress-io/cypress/issues/1319#issuecomment-596033763 ([example](https://github.com/jrwebdev/typescript-jest-cypress/blob/master/src/example.cy.ts))
- [ ] make sure it works properly with `nextjs` setup
  - https://github.com/cypress-io/cypress/tree/254eb47d91c75a9f56162e7493ab83e5be169935/npm/react/examples/nextjs

### Follow-up PRs
  - set up Apollo client and show how to mock (intercept) API requests

## worth mentioning commits

- https://github.com/natterstefan/nextjs-template/pull/3/commits/8d7488c057d0a1f3949d05a6aff8f0e3fd2f3219: enables usage of `jest`'s `expect` next to `cypress`\`s

## What I did

- added Cypress with basic setup commands, plugins, and first few tests

## How to test

- e.g. with `test:cypress:ci`

## Screenshots

404
